import "../styles/app.scss";
import { Inter } from "next/font/google";
import Header from "./Header";
import ReduxStoreProvider from "../../store/Provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <ReduxStoreProvider>
          {" "}
          <Header />
          {children}
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
